from enum import Enum


class ReportTypes(Enum):
    # People Insights
    SHOPPER_PROFILE = 'Shopper Profile'
    BASKET_AFFINITY = 'Basket Affinity'
    HOUSEHOLD_AFFINITY = 'Household Affinity'
    CROSS_PURCHASE = 'Cross Purchase'
    PSYCHOGRAPHICS = 'Psychographics'
    MEDIA_CONSUMPTION = 'Media Consumption'
    # Shopper Insights
    SHOPPER_METRICS = 'Shopper Metrics'
    LEAKAGE_TREE = 'Leakage Tree'
    SHOPPER_HISTOGRAM = 'Shopper Histogram'
    TRIP_TYPE_PROFILE = 'Trip Type Profile'
    LAPSED_REPEAT_NEW = 'Lapsed, Repeat, New'
    TRIP_CIRCUITS = 'Trip Circuits'
    PROMOTION_EFFECTIVENESS = 'Promotion Effectiveness'
    RETAILER_SHARE_WALLET = 'Retailer Share of Wallet'
    STORE_DIAGNOSTICS = 'Store Diagnostics'
    STORE_LOYALTY_FLOW = 'Store Loyalty Flow'
    # Brand Insights
    BRAND_DIAGNOSTICS = 'Brand Diagnostics'
    DATA_EXPLORER = 'Data Explorer'
    SHARE_EXPLORER = 'Share Explorer'
    MOMENTS_OF_TRUTH = 'Moments of Truth'
    BRICKS_AND_CLICKS = 'Bricks and Clicks'
    BUYER_LOYALTY_FLOW = 'Buyer Loyalty Flow'
    BRAND_SWITCHING = 'Brand Switching'
    EBSOVA = 'Existing Brand Source of Volume'
    PEOPLE_SCORECARD = 'People Scorecard'
    TRENDED_METRICS = 'Trended Metrics Scorecard'
    # New Item Insights
    NEW_ITEM_TRACKER = 'New Item Tracker'
    NEW_ITEM_SOVA = 'New Item Source of Volume'
    # Promo Insights
    PROMOTION_SCORECARD = 'Promotion Scorecard'
    EVENT_ANALYSIS = 'Event Analysis'
    RETAILER_CIRCULAR_ANALYSIS = 'Retailer Circular Analysis'
    # Instant Surveys
    LEAKAGE = 'Leakage Survey'
    LAPSING_BRAND = 'Lapsing Brand Survey'
    CONCEPT_SCREENING = 'Concept Screening Survey'
    QUICK_PULSE = 'Quick Pulse Survey'
    # Tools Module
    PRODUCT_HIERARCHY = 'Product Hierarchy Explorer'
    STORE_HIERARCHY = 'Store Hierarchy Explorer'
    PEPSI_SHOPPER_CIRCUITS = 'PepsiCo Shopper Circuits'
    # Labs Module
    COUNT_REPORT = 'Count Report'
    USER_ID_FETCH = 'User ID Fetch'
    PROMO_PG = 'Promotion People Group Creator'
    SURVEY_SAMPLE = 'Survey Sample Report'
    HIGH_MED_LOW = 'High, Medium, Low'
    # Report Prefixes
    PREFIX = '[E2E] '
    PREFIX_CG = '[E2E - CG] '
    PREFIX_RV = '[E2E - RV] '


class PageTitles(Enum):
    HISTORY = 'ALL MY REPORTS'
    SURVEYS = 'Instant Surveys'
    PEOPLE_GROUPS = 'ALL PEOPLE GROUPS'
    TRIP_GROUPS = 'ALL TRIP GROUPS'
    PEOPLE = 'People Insights'
    SHOPPER = 'Shopper Insights'
    BRAND = 'Brand Insights'
    NEW_ITEM = 'New Item Insights'
    PROMO = 'Promo Insights'
    INSTANT_SURVEYS = 'Select a Survey Type'
    TOOLS = 'Tools'
    PROD_GROUPS = 'ALL MY PRODUCT GROUPS'
    STORE_GROUPS = 'ALL MY STORE GROUPS'
    LABS = 'Numerator Labs'
    SETTINGS = 'Test 2.0'
    HELP_CENTER_SELECTOR = "[href='http://help.insights.numerator.com/']"
    RENAME_MODAL = 'RENAME REPORT'
    SHARE_MODAL = 'EXPORT'


class Prompts(Enum):
    ADULT_GENDERS = 'Any Adult Gender Present on trip'
    ANY = 'Any'
    BANNER = 'Any Banner'
    BENCHMARK = 'Benchmark'
    CATEGORY = 'Any Category'
    CHANNEL_PARENT_CHANNEL = 'Any Parent Channel or Channel'
    CHANNEL_WEIGHT = 'Any Channel Weight'
    CHILDREN = 'Any Children'
    COMP_AREA = 'Competitive Area'
    COMP_BANNER = 'Any Comparison Banner'
    COMP_CHANNEL = 'Any Competitive Channel'
    COMP_PRODUCT = 'Any Comparison Product'
    CUSTOM_SELECT = 'Any Custom Selection'
    DATE_RANGE = 'Any Date Range'
    DAY_OR_TIME = 'Any Day or Time'
    DEMOGRAPHIC = 'Any Demographic'
    LEVEL = 'Any Level'
    LOCATION = 'Any Location'
    METRICS = 'Any Metrics'
    NEW_ITEMS = 'All New Items'
    NONE = 'None'
    NONE_SELECT = 'None Selected'
    NUM_WEEKS = 'Any number of weeks'
    PARENT_CHANNEL = 'Any Parent Channel'
    PG = 'Any People Group'
    PORTFOLIO = 'No Other Products In Portfolio'
    PRODUCT = 'Any Product'
    PRODUCTS = 'All Products'
    PRODUCT_LEVEL = 'Any Product Level'
    PROMO = 'Any Existing Promotion'
    PROMO_DATES = 'Any Promotion Dates'
    PURCHASED = 'Purchased'
    RETAILER = 'Any Retailer'
    SAME_CAT = 'Same as Categories Prompt answer'
    SAME_PROD = 'Same as Product Prompt answer'
    SAME_PRODUCT_LEVEL = 'Same as Selected Product'
    SAME_PRODUCT_LEVEL_LOWER = 'Same as selected Product'
    SAME_STORE = 'Same as Selected Store'
    SAME_STORE_LEVEL = 'Same level as store selected'
    SHOPPERS = 'All Shoppers'
    SPLIT = 'Any Split'
    STATIC = 'Any Static Group'
    STORE = 'Any Store'
    STORE_LEVEL = 'Any Store Level'
    STORES = 'All Stores'
    TCC_TENURE = 'TCC and Tenure (Default)'
    TG = 'Any Trip Group'
    TIME_INTERVAL = 'Any Time Interval'
    TRIP_ATTR = 'Any Trip Attribute'
    TRIP_CIRCUIT_TYPE = 'Any Trip Circuit Type'


class PromptElements(Enum):
    ADULT_GENDERS = 'Adult genders on trip'
    AGE_BRACKETS = 'Age (Brackets)'
    AGE_GEN = 'Age (Generation)'
    AND = 'AND'
    AVG_SELECTION = 'Average of Selection'
    BABY_TOY = 'Baby & Toy'
    BANNER = 'Banner'
    BEAUTY = 'Beauty'
    BENCHMARK = 'Benchmark'
    BIN_AVG_SPEND = 'Average Spend per Unit (per Household)'
    BIN_ITEM_SPEND_HH = 'Total Item Spend Per Household'
    BIN_SPEND_UNIT_TRIP = 'Average Spend per Unit (per Trip)'
    BIN_TOTAL_SPEND = 'Total Spend (per Household)'
    BRAND = 'Brand'
    BRICK_MORTAR = 'Brick and Mortar'
    CANCEL = 'Cancel'
    CATEGORIES = 'Categories'
    CATEGORY = 'Category'
    CG_BRAND = 'Brand Level'
    CG_CAT = 'Category Level'
    CG_DEPARTMENT = 'Department Level'
    CG_MAJOR_CAT = 'Major Category Level'
    CG_PARENT_BRAND = 'Parent Brand Level'
    CHANNEL = 'Channel'
    CHANNEL_WEIGHTS = 'Channel Weights'
    CLOSE_STATEMENT = ')'
    CLOSED_CONDITION = ') '
    CLUB = 'Club'
    COMP_CHANNEL = 'Competitive Channel'
    CORE_METRICS = 'Core Metrics'
    CUSTOM_FILTERS = 'Custom Filters'
    CUSTOM_STORE_GROUPS = 'Custom Store Groups'
    CUSTOM_TIME = 'Custom Time Period'
    DATE_RANGE = 'Date Range'
    DAY_OF_WEEK = 'Day of Week'
    DAY_PART = 'Day Part'
    DAY_TIME = 'Day or Time'
    DEFAULT = 'Default'
    DEMO_ATTR = 'Demographic Attributes'
    DEMOGRAPHICS = 'Demographics'
    DEPARTMENT = 'Department'
    DOLLAR = 'Dollar'
    DRUG = 'Drug'
    ECOMMERCE = 'eCommerce'
    FIXED_FILTERS = 'Fixed Filters'
    FMCG = 'FMCG'
    FOOD = 'Food'
    FROM_PRIOR_PERIOD = 'From the Prior Period'
    FULL = 'Full'
    GEO_ATTR = 'Geography Attributes'
    GEOGRAPHY = 'Geography'
    GREATER_EQUAL = 'Greater than or equal to'
    HEALTH = 'Health'
    IN = 'IN'
    NOT_IN = 'NOT IN'
    INCLUDE_OUTLIERS = 'Include Outliers'
    KIDS = 'Kids present on trip'
    LATEST_3_MONTHS = 'Latest 3 Complete Months'
    LATEST_6_MONTHS = 'Latest 6 Complete Months'
    LATEST_12_MONTHS = 'Latest 12 Complete Months'
    LATEST_12_WEEKS = 'Latest 12 Weeks'
    LATEST_52_WEEKS = 'Latest 52 Weeks'
    LEAKAGE_METRICS = 'Leakage Metrics'
    LOYALTY_METRICS = 'Loyalty Metrics'
    MAJOR_CAT = 'Major Category'
    MASS = 'Mass'
    MAX_2 = 'Maximum number of answers (2) has been reached.'
    MAX_3 = 'Maximum number of answers (3) has been reached.'
    MAX_5 = 'Maximum number of answers (5) has been reached.'
    MAX_8 = 'Maximum number of answers (8) has been reached.'
    MILITARY = 'Military'
    NUM_WEEKS_AFTER = 'Number of Weeks After Event'
    NUM_WEEKS_BEFORE = 'Number of Weeks Before Event'
    ONLINE = 'Online'
    PARENT_BRAND = 'Parent Brand'
    PARENT_CHANNEL = 'Parent Channel'
    PEPSI_ANALYSIS_RETAILER = 'Pepsi Analysis Retailer'
    PEPSI_CHANNEL = '(Pepsi) Channel Groups wo Total'
    PEPSI_EDIBLE = '(Pepsi) Total Edible Categories'
    PEPSI_WHOLE_FOODS = '(Pepsi) Whole Foods Comp Set'
    PERCENT_TRIPS = '% of Trips'
    PG = 'People Group'
    POST_PERIOD = 'Post Period'
    PRE_PERIOD = 'Pre Period'
    PREV_PERIOD_OPTIONS = 'Previous Period Options'
    PRIOR_PERIOD = 'Prior Period'
    PROD_ATTR = 'Product Attributes'
    PROD_STORE_ATTR = 'Product and Store Attributes'
    PRODUCT = 'Product'
    PROJ_HH = 'Projected Households'
    PROJ_METRICS = 'Projected Metrics'
    PROMO_DATES = 'Promotion Dates'
    REMOVE_OUTLIERS = 'No, Remove Outliers'
    RETAILER = 'Retailer'
    RETAILER_BANNER = 'Retailer or Banner'
    ROLL_12_QUARTER = 'Rolling 12 months by Quarter'
    RUN_REPORT = 'Run Report'
    SAME_WEEK_CIRCUIT = 'Same Week Trip Circuits (Mon-Sun)'
    SECTOR = 'Sector'
    SHARE_CAT_UNITS = 'Share of Category Req. (Units)'
    SHARE_TOTAL_METRICS = 'Share of Total Metrics'
    SHARE_WALLET = 'Share of Wallet'
    SPECIAL_FOOD = 'Specialty Food Retailer'
    SPEND_TRIP = 'Spend per Trip'
    SPLIT_OPTIONS = 'Split Options'
    STATIC_GROUP = 'Static Group'
    STATIC_OPTIONS = 'Static Options'
    STORE_ATTR = 'Store Attributes'
    STORE_CHANNEL = 'Store or Channel'
    SUBCAT = 'Subcategory'
    SUB_CHANNEL = 'Subscribed Channel'
    TCC_TENURE = 'TCC and Tenure (Default)'
    TG = 'Trip Group'
    TOP_STORES = 'Top Stores'
    TOTAL_TRIP_COUNT = 'Total Trip Count (across all baskets)'
    TRANSCRIPTION_LEVEL = 'Transcription Level'
    TRIP_CIRCUIT_TYPE = 'Trip Circuit Type'
    TWO_TRIPS = '2+ Trips'
    WEEKS_13 = '13 Weeks'
    WEEKS_26 = '26 Weeks'
    WEEKS_52 = '52 Weeks'
    WITHIN_SAME_DAY = 'Within the same day'
    YEAR_AGO = 'Year Ago'
    YEAR_AGO_PRIOR = 'Year Ago or Prior Period'


class Attributes(Enum):
    ANY = 'any'
    CLASS = 'class'
    COMPLETE = 'complete'
    RESULT = 'result'
    SELECTED = 'selected'
    SPAN = 'span'
    TAG_I = 'i'
    TAG_LI = 'li'
    TAG_UL = 'ul'
    VALUE = 'value'


class NavLinks(Enum):
    # Nav Links
    HISTORY = 'history'
    SURVEYS = 'surveys'
    PG_MOD = 'people-groups'
    # People Insights
    PEOPLE_INSIGHTS = 'people-insights'
    SHOPPER_PROFILE = 'shopper-profile'
    BASKET_AFFINITY = 'basket-affinity'
    HOUSEHOLD_AFFINITY = 'household-affinity'
    CROSS_PURCHASE = 'cross-purchase'
    PSYCHOGRAHPICS = 'psychographics'
    MEDIA_CONSUMPTION = 'media-consumption'
    # Shopper Module
    SHOPPER_MOD = 'shopper'
    SHOPPER_MOD_LINK = '/#/login?next=/shopper'
    SHOPPER_METRICS = 'shopper-metrics'
    LEAKAGE_TREE = 'leakage-tree'
    SHOPPER_HISTOGRAM = 'shopper-histogram'
    TRIP_TYPE_PROFILE = 'trip-type-profile'
    LAPSED_REPEAT_NEW = 'lapsed-repeat-new'
    TRIP_CIRCUITS = 'trip-circuits'
    PROMO_EFFECTIVENESS = 'promotion-effectiveness'
    RETAILER_SOW = 'retailer-share-wallet'
    STORE_DIAGNOSTICS = 'store-diagnostics'
    STORE_LOYALTY_FLOW = 'store-loyalty-flow'
    # Brand Module
    BRAND_MOD = 'brand'
    BRAND_DIAGNOSTICS = 'brand-diagnostics'
    DATA_EXPLORER = 'data-explorer'
    SHARE_EXPLORER = 'share-explorer'
    MOMENTS_OF_TRUTH = 'moments-of-truth'
    BRICKS_CLICKS = 'bricks-clicks'
    BUYER_LOYALTY_FLOW = 'buyer-loyalty-flow'
    BRAND_SWITCHING = 'brand-switching'
    EBSOVA = 'ebsova'
    PEOPLE_SCORECARD = 'people-scorecard'
    TRENDED_METRICS = 'trended-metrics'
    # New Item Module
    NEW_ITEM_MOD = 'new-item'
    NEW_ITEM_TRACKER = 'new-item-tracker'
    NEW_ITEM_SOVA = 'new-item-sova'
    # Promo Insights
    PROMO_INSIGHTS = 'trade-insights'
    PROMO_SCORECARD = 'promotion-scorecard'
    EVENT_ANALYSIS = 'event-analysis'
    RETAILER_CIRCULAR_ANALYSIS = 'retailer-circular-analysis'
    # Instant Surveys
    INSTANT_SURVEYS = 'instant-surveys'
    LEAKAGE = 'leakage-instant-survey-type'
    LAPSING_BRAND = 'lapsing-brand-instant-survey-type'
    CONCEPT_SCREENING = 'concept-screening-instant-survey-type'
    QUICK_PULSE = 'quick-pulse-instant-survey-type'
    # Tools Module
    TOOLS_MOD = 'tools'
    PRODUCT_HIERARCHY = 'product-hierarchy-explorer'
    STORE_HIERARCHY = 'store-hierarchy-explorer'
    DEMOGRAPHICS_PROFILE = 'demographics-profile'
    PEPSI_SHOPPER_CIRCUITS = 'pepsi-shopper-circuits'
    # Labs Module
    LABS_MOD = 'isc-labs'
    COUNT_REPORT = 'count-report'
    USER_ID_FETCH = 'user-id-fetch'
    PROMO_PG = 'promotion-people-group'
    SURVEY_SAMPLE = 'survey-sample'
    HIGH_MED_LOW = 'high-med-low'
    # Advanced Groups
    ADV_GROUPS = 'product-groups'


class Selectors(Enum):
    ACTIVE_TAB = '.nav-link.active'
    ACTIVE_TOGGLE = '.btn-group .selector-btn .active'
    ADV_FILTER = '.filter-block .answer'
    ADV_OPTIONS = '.advanced-filters .header .isc-cursor-pointer'
    ALERT_TEXT = '.isc-alert .alert-text'
    BIN_HIGH = '.prompt-metric-qualification .input_container_text_box_high'
    BIN_LOW = '.prompt-metric-qualification .input_container_text_box_low'
    BIN_LOWER = '.prompt-metric-qualification .input_container_text_box_lower_bound'
    BIN_MED = '.prompt-metric-qualification .input_container_text_box_medium'
    BIN_UPPER = '.prompt-metric-qualification .input_container_text_box_upper_bound'
    BIN_WIDTH = '.prompt-metric-qualification .input_container_text_box_bin_width'
    BODY = 'body'
    BREADCRUMBS = '.prompt-breadcrumbs span'
    CARD_TITLES = "//div[@class='card-col title-description']//div[@class='title']"
    CELL = 'sort-body-cell'
    CELL_SORT = 'sort-header-cell'
    CELL_TEXT = '.text-container.ellipsify'
    CHART_LEGEND = '.highcharts-legend-item tspan'
    CHECKBOX = '.isc-check-box'
    CLEAR_PROMPT = '.insights-icon-remove.clickable'
    CLOSE_MESSAGE = '.notification-dismiss'
    CLOSE_NOTIF = '.notifications-wrapper .notification-dismiss'
    CLOSED_CONDITION = "//div[@role='combobox']/div/div/span"
    COMBO_BOX = "[role='combobox'] input"
    CONFIRM_DELETE = '.cta-buttons-wrapper .delete.btn'
    COPIED_TABLE = '.rendered-table-controls .copy-table-btn .copied'
    COPY_TABLE = '.rendered-table-controls .copy-table-btn'
    CREATE_GROUP_BTN = '.create-group-btn'
    CUSTOM_DATE = '#date-range-picker input'
    DETAILS_ANSWERS = '.modal-body .cta-modal-details-answer'
    DETAILS_DESCRIPTION = '.modal-body .cta-modal-description'
    DETAILS_PROMPT = '.modal-body .cta-modal-details-prompt-section'
    DETAILS_TITLE = '.modal-body .cta-modal-details-name'
    DIAGRAM_CANVAS = '.html2canvas-container'
    DOWNLOAD_BUTTON = '.export-png-btn'
    DROP = '.caret'
    DROPDOWN = '.dropdown-selector'
    DROPDOWN_NAME = '.selector-label'
    DROPDOWN_OPTION = '.dropdown-menu li'
    DROPDOWN_SELECTOR = '.dropdown .btn-default'
    EMPTY_SEARCH = '.empty-table'
    FILTER_DROPDOWN = '.dropdown .dropdown-toggle'
    FOLDER = '.folder-icon + .prompt-element-label'
    FOLDER_BREADCRUMBS = '.breadcrumbs .folder .ellipsify'
    FOLDER_NAME = '.folder-name.ellipsify'
    # nosec: B105 CSS selector, not password
    FORGOT_PASSWORD = 'span.forgot-password'
    GROUPS_FOLDER_OPTIONS = "//div[@class='actions']/div"
    GROUPS_NAME_MSG = '.prompt-container .review-description'
    GROUPS_NEXT_BTN = '.btn-toolbar .btn-info'
    GROUPS_ROW_OPTIONS = "//div[@class='actions']/div/div"
    GROUPS_SHARE = '.all-vs-fav .view-toggle'
    GROUPS_TITLE = '.folder .ellipsify'
    GROUPS_TOGGLE = '.btn-default.selector-btn'
    HEADER_CELL = '.ReactVirtualized__Table__headerColumn'
    HEADER_ROW = 'ReactVirtualized__Table__headerRow'
    HIERARCHY_NAME = 'attribute-container'
    HIGH_LEGEND_LABEL = '.highcharts-legend .highcharts-legend-item'
    ICON_CLASS = 'insights-icon-folder'
    INPUT = '.prompt-element li'
    INTERCOM = "//div[@id='intercom-container']/div/iframe"
    LEGEND_LABEL = '.legend .legend-label'
    LOGIN = '#form-login .button'
    LOGO = 'div.logo'
    LOGOUT = '.header-row .logout'
    MEATBALLS = '.insights-bigcta-meatballs'
    METRIC_TEXTBOX = '.prompt-metric-qualification #text-box-input'
    MOD_NAV_LINK = "#sidebar .section [href='#/{}']"
    MOD_TITLE = '.main-header h1'
    MODAL_BUTTON = '.modal-body button'
    MODAL_CLOSE = '.modal-body .insights-icon-remove'
    MODAL_TITLE = '.modal-body .cta-modal-label'
    MODAL_WARNING = '.modal-content .isc-tiny-warning'
    MOT_CARD_TITLES = "//div[@class='card-col']//div[@class='title']"
    OPTION_LIST = '.prompt-block-wrapper .checkbox-icon'
    PASSWORD = 'password'  # nosec: B105 test environment password
    PG_LIST_OPTIONS = "[role='listbox'] li"
    PG_MODAL_INPUT = '.cta-input-wrapper input'
    PG_MODAL_SAVE = '.modal-body button'
    PROMPT = '.prompt-answer-container .answer'
    PROMPT_BLOCK = "//div[@role='combobox']/div/div/div"
    PROMPT_ELEMENT = '.elements .prompt-element'
    PUB_SHARE_MESSAGE = '.modal-body #share-message'
    RANK_ATTR = '.answers-ranker li'
    RANK_ATTR_DOWN = '.ranker-element .insights-icon-tri-down-filled'
    RANK_ATTR_UP = '.ranker-element .insights-icon-tri-up-filled'
    READ_ONLY_MESSAGE = '.bg-success.announcement.announcement-flex'
    RENAME_INPUT = '.cta-input-wrapper input'
    RENAME_SAVE = '.cta-input-wrapper .btn'
    REPORT_BUTTON = '.report-buttons button'
    REPORT_CONTAINER = '#insights-container .prompt-container'
    REPORT_HEADER = '.report-header .report-content'
    REPORT_NAME = 'doc-name'
    REPORT_NAV_LINK = ".report-content a[href='#/document/{}']"
    REPORT_RUNNING = '.text-center .message'
    REPORT_STATUS = 'status-indicator'
    REPORT_TITLE = '.report-header h1'
    ROW = '.ReactVirtualized__Table__row'
    ROW_COL_IDX = "[aria-colindex='{}']"
    ROW_COLUMN = '.ReactVirtualized__Table__rowColumn'
    ROW_DELETE = '.actions .remove'
    ROW_DOC_NAME = '.doc-name'
    ROW_NAME = '.name-cell'
    ROW_OPTIONS = "//div[@class='actions']/div"
    SEARCHBOX = '.text-box-container #text-box-input'
    SHARE = '.report-tools .insights-bigcta-export'
    SHARE_BUTTON = '.modal-footer .button'
    SHARE_CHECK = '.ReactVirtualized__Grid__innerScrollContainer .isc-check-box'
    SHARE_CLOSE = '.modal-body .isc-tiny-remove'
    SHARE_INPUT = '.modal-body .text-box-container #text-box-input'
    SHARE_LINK = '.modal-body #cta-share-input'
    SHARE_TITLE = '.modal-header .modal-title'
    SHARE_TOGGLE = '.modal-body .round'
    SHARE_USER = '.users-list .ReactVirtualized__Grid__innerScrollContainer'
    SURVEY_NAV_LINK = ".report-content a[href='#/instant-surveys/{}']"
    TAB = '.tab-nav-bar .nav-link'
    TAB_PAGE = '.tabs-container'
    TABLE = '.ReactVirtualized__Table'
    TOGGLE_BTN = '.btn-group .selector-btn'
    TREE_TITLES = "//div[@class='tree-row row']//div[@class='title']"
    USER = 'user'
    USERNAME = 'username'


class GroupsTitles(Enum):
    PG_CREATE = 'Create a People Group'
    PG_NAME = "Give your People Group a name you'll remember!"
    PG_DETAIL = 'This is a regular People Group.'
    TG_CREATE = 'Create a Trip Group'
    TG_NAME = "Give your Trip Group a name you'll remember!"
    TG_DETAIL = 'This is a regular Trip Group.'
    AG_CREATE = 'Create a Product Group'
    STORE_CREATE = 'Create a Store Group'
    AG_NAME = 'Name your Folder and Product Group'
    SG_NAME = 'Name your Folder and Store Group'
    PEOPLE_NAME = '[E2E] TEST PG'
    PEOPLE_RENAME = '[E2E] TEST PG RENAMED'
    TRIP_NAME = '[E2E] TEST TG'
    TRIP_RENAME = '[E2E] TEST TG RENAMED'
    ADV_FOLDER = '[E2E] TEST PG FOLDER'
    ADV_NAME = '[E2E] TEST PG'
    ADV_ADD = '[E2E] TEST PG ADD'
    ADV_RENAME = '[E2E] TEST PG RENAMED'
    STG_FOLDER = '[E2E] TEST STG FOLDER'
    STG_NAME = '[E2E] TEST STG'
    STG_ADD = '[E2E] TEST STG ADD'
    STG_RENAME = '[E2E] TEST STG RENAMED'
    SHARE_SEARCH = 'One'
    SHARE_USER = 'Test, One'
    SHARE_BUTTON = 'Share with {} colleague'


class ReportTabs(Enum):
    ADVERTISING = 'Advertising'
    BASIC_METS = 'Basic Metrics'
    BASKET_COMP = 'Basket Composition'
    BASKET_MET = 'Basket Metrics'
    BENCHMARK = 'Benchmark'
    BENCHMARKS = 'Benchmarks'
    BRAND_SHIFT = 'Brand Shift'
    BRAND_SHIFTING = 'Brand Shifting'
    BRAND_SWITCH_DETAIL = 'Brand Switching Detail'
    BRAND_SWITCH_SUM = 'Brand Switching Summary'
    BRAND_TREE = 'Brand Tree'
    BUYER_OPINIONS = 'Buyer Opinions'
    BUYER_OVERLAP = 'Buyer Overlap'
    CAT_CHURN = 'Category Churn'
    CAT_EXP_CON = 'Category Expansion & Contraction'
    CAT_SUMMARY = 'Category Summary'
    CHAN_CIRCUITS = 'Channel Circuits'
    CHAN_SHIFT = 'Channel Shift'
    CLOSED_PROD = 'Closed Circuits, Product'
    CLOSED_STORE = 'Closed Circuits, Store'
    COMMON_CIRCUITS = 'Common Circuits'
    COMP_MOT = 'Compare Moments of Truth'
    COMP_SUMMARY = 'Competitive Summary'
    COMP_SURVEY = 'Compare Survey Results'
    COMPARISON = 'Comparison'
    CONVERSION = 'Conversion'
    DEMO = 'Demographics'
    EATING = 'Eating'
    EX_SURVEY = 'Explore Survey'
    GAIN_LOSS = 'Gains & Losses Grid'
    HEALTH_SUS = 'Health & Sustainability'
    HH = 'Household'
    HH_COUNT = 'HH Count'
    INCREMENTALITY = 'Incrementality'
    INCREMENT_DETAIL = 'Incrementality Detail'
    KPI = 'Key Performance Indicators'
    LEAKED_PROD = 'Leaked Circuits, Product'
    LEAKED_STORE = 'Leaked Circuits, Store'
    LISTENING = 'Listening'
    LOYALTY_SHIFT = 'Loyalty Shifting'
    LRN = 'Lapsed, Repeat, New'
    PAY_METHODS = 'Payment Methods'
    PEN_GRID = 'Penetration Grid'
    PEP_EDIBLES = 'Pepsi Edibles'
    PROD_MATRIX = 'Product Matrix'
    PROD_PREF = 'Product Preference'
    PROMO_DETAILS = 'Promotion Details'
    PROMO_SUMMARY = 'Promotion Summary'
    READING = 'Reading'
    REPEAT_DRIVERS = 'Repeat Drivers'
    RETAIL_CIRCUITS = 'Retailer Circuits'
    RETAILER_DRIVERS = 'Retailer Drivers'
    RETAILER_PREF = 'Retailer Preference'
    SHARE_CIRCUITS = 'Share of Circuits'
    SHARE_SPEND = 'Share of Spend'
    SHIFTING = 'Shifting'
    SHOPPING = 'Shopping'
    SOCIAL_MEDIA = 'Social Media'
    SOV = 'Source of Volume'
    SPORTS = 'Sports Fandom'
    STORE_PREF = 'Store Preference'
    STORE_SWITCH = 'Store Switching'
    STORES_SHOPPED = 'Stores Shopped'
    SUB_TRIPS = 'Substitutable Trips'
    SUMMARY = 'Summary'
    SWITCHING = 'Switching'
    TIMING = 'Timing'
    TOP_ITEMS = 'Top Items'
    TOP_PRODUCTS = 'Top Products'
    TOP_STORES = 'Top Stores'
    TOTAL_COMP = 'Total Composition'
    TOTAL_EDIBLES = 'Total Edibles'
    TREE_DIAGRAM = 'Tree Diagram'
    TRIAL_REPEAT = 'Trial & Repeat'
    TRIP_TYPE = 'Trip Type'
    TRIP_TYPE_DIST = 'Trip Type Distribution'
    USER_ID = 'User ID List'
    WATCHING = 'Watching'


class Sort(Enum):
    ASC = 'asc'
    DESC = 'desc'
    NATURAL = 'natural'
